Repository kandidatg11/behaviour-activation, pull requests merged in 2021-04, with the labels that each got.

#5 Establish a code style
  README.md
Labels: documentation

#4 Basic navigation routes
  App.tsx
  app.json
  package-lock.json
  package.json
  src/components/ActivityScreen.tsx
  src/components/CalendarScreen.tsx
  src/components/CustomNavigationBar.tsx
  src/components/InformationScreen.tsx
  src/components/RootNavigator.tsx
  src/components/ValuesScreen.tsx
Labels: enhancement

#3 Storage implementation
  .gitignore
  src/storage/activities.tsx
  src/storage/calendar.tsx
  src/storage/components/storageTest.tsx
  src/storage/icons.tsx
  src/storage/index.tsx
  src/storage/people.tsx
  src/storage/settings.tsx
  src/storage/storage.tsx
  src/storage/utils.tsx
  src/storage/values.tsx
Labels: enhancement

#6 Rewrite storage to use a context
  App.tsx
  babel.config.js
  src/storage/activities.tsx
  src/storage/calendar.tsx
  src/storage/components/storageTest.tsx
  src/storage/context.tsx
  src/storage/icons.tsx
  src/storage/index.tsx
  src/storage/package.json
  src/storage/people.tsx
  src/storage/settings.tsx
  src/storage/storage.tsx
  src/storage/values.tsx
  tsconfig.json
Labels: enhancement

#10 Beginning of calendar
  README.md
  src/CustomTheme.tsx
  src/components/CalendarScreen.tsx
  src/components/calendar/CalendarList.tsx
  src/components/calendar/CalendarListItem.tsx
  src/components/calendar/CalendarListSection.tsx
  src/language/en.json
  src/language/sv.json
  src/storage/calendar.tsx
Labels: enhancement

#21 Fix dependency cycle
  src/components/calendar/CalendarList.tsx
  src/components/calendar/CalendarListItem.tsx
  src/components/calendar/CalendarListSection.tsx
  src/storage/activities.tsx
  src/storage/calendar.tsx
  src/storage/constants.tsx
  src/storage/context.tsx
  src/storage/icons.tsx
  src/storage/people.tsx
  src/storage/settings.tsx
  src/storage/types.tsx
  src/storage/values.tsx
Labels: bug

#24 Add settings view
  babel.config.js
  src/components/ActivityScreen.tsx
  src/components/CalendarScreen.tsx
  src/components/CustomNavigationBar.tsx
  src/components/IconMeny.tsx
  src/components/InformationScreen.tsx
  src/components/SettingsScreen.tsx
  src/components/ValuesScreen.tsx
  src/components/activity/ActivityRegistrator.tsx
  src/components/activity/IconList.tsx
  src/components/settings/IconCustomizer.tsx
  src/components/settings/IconWithText.tsx
  src/components/settings/LanguageMenu.tsx
  src/components/settings/NotificationSwitch.tsx
  src/components/settings/package.json
  src/language/en.json
  src/language/index.tsx
  src/language/sv.json
  src/storage/icons.tsx
  tsconfig.json
Labels: enhancement

#29 Add, modify and removal of calendar entries
  babel.config.js
  src/components/CalendarScreen.tsx
  src/components/ChoiceBasedTextInput.tsx
  src/components/CustomNavigationBar.tsx
  src/components/calendar/CalendarList.tsx
  src/components/calendar/CalendarListItem.tsx
  src/components/calendar/CalendarRegistrator.tsx
  src/storage/calendar.tsx
  src/storage/types.tsx
  src/utils/index.tsx
  src/utils/package.json
  tsconfig.json
Labels: enhancement
